"""Repository gate: the desktop client's transport design cannot regress
into a host-administration channel, and cannot stop verifying certificates.

The client reaches the service at a configured secure endpoint and
authenticates every request with a device credential. Host shell access is
the operator's administration channel; it is not how the application talks
to the service, and no shipped file may teach otherwise.

These are text gates, deliberately in the repository suite rather than the
client's own: they cover files from three different trees (client sources,
client tests, the client guide, the Compose file), and they must run on
every pull request without a Windows runner or the client's dependencies.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

# (a) The scan scope is the UNION of the shipped client surface and the
#     deployment files that describe how it is reached.
#
# The client side is scanned by RECURSION over `client/`, not by a list: a
# list has to be maintained, and a file added to the client root tomorrow
# would be silently out of scope. Build artefacts and virtual environments
# are excluded because they are third-party bytes, not shipped surface.
#
# The owner-private web presentation layer is scanned by the same recursion,
# and for the same reason the client tree is. It is a THIRD surface reached
# over the network by a person, and the revoked design - "get to it by opening
# a tunnel to the host" - is exactly as available a wrong answer there as it
# was for the desktop client. Before this tree was listed here the whole
# package sat outside the scan, so the guard would have stayed green over
# anything written in it: that green would have been the absence of a check,
# not the absence of an offence.
#
# It lands under the STRICT rule automatically, because `_offending_lines`
# derives strictness as "not in RECIPE_ONLY_PATHS" - the default is strict and
# leniency is the thing that has to be asked for by name.
SCANNED_TREES = (
    ROOT / "client",
    ROOT / "src" / "wuwaterm_api" / "web",
)
EXCLUDED_DIR_NAMES = {
    ".venv",
    "venv",
    "build",
    "dist",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}
# `pip install -e client[dev]` writes client/src/wuwaterm_client.egg-info/*.txt,
# and `.txt` is a scanned suffix - generated bytes that would be scanned as
# though they were authored.
EXCLUDED_DIR_SUFFIXES = (".egg-info",)
SCANNED_FILES = (
    # The runbook. tests/test_deploy_scripts.py pins four literal recipes in
    # it; this adds the pattern scan, so a spelling those literals miss
    # (`ssh -fNL`, `autossh`, prose) is caught as well.
    ROOT / "docs" / "deployment.md",
    # The web layer's operator guide. It is here for the same reason
    # deployment.md is: it tells a reader how the surface is reached, so it is
    # a place where "reach it by opening a tunnel" could be written down. It is
    # NOT in RECIPE_ONLY_PATHS, so it gets the strict rule - unlike the
    # deployment runbook it has no legitimate need to name the administration
    # channel at all.
    ROOT / "docs" / "web-presentation-layer.md",
    *sorted((ROOT / "deploy").glob("*.yml")),
    *sorted((ROOT / "deploy").glob("*.yaml")),
    # The deployment scripts. A helper that grew a forwarded port would
    # otherwise be the one place nothing looked - a shell script is where such
    # a thing naturally appears.
    *sorted((ROOT / "deploy").glob("*.sh")),
)
SCANNED_SUFFIXES = {".py", ".md", ".yml", ".yaml", ".spec", ".ps1", ".txt", ".toml"}

# Two rules, because the two surfaces have different jobs - but ONE source of
# truth for the forwarding half, so the strict rule is a superset of the
# lenient one by construction rather than by two lists staying in step.
#
# A forwarding instruction is written in one of two ways, and they need two
# different readers:
#
#   PROSE - "tunnel", "port-forward", "a forwarded port", `LocalForward` - is
#   matched anywhere on the line, because it means the same thing wherever it
#   appears, quoted or not.
#
#   A COMMAND is matched by PARSING it (`_ssh_option_flags`). Five rounds of
#   review went into learning that a regex cannot find where ssh's own
#   arguments end: the whole line made `ssh <vps> 'chmod -R 755 /opt'` an
#   offence; blanking quotes lost `ssh -L "8787:…"`; stopping at the first
#   quote lost `ssh -i "a key" -L 8787:…` and still rejected
#   `ssh <vps> curl -L https://…`. `ssh -h` states the structure in one line -
#   `ssh [options] destination [command [argument ...]]` - and reading the
#   option letters is both simpler and exact. Inside ssh's own options, `-L`,
#   `-R` and `-D` ARE forwarding whatever their argument looks like, so the
#   shape rules that used to be needed are gone with the guessing.
#
# The shapes below survive for one case only: a line with no `ssh` on it at
# all, where there is nothing to parse.
_SPEC_LR = r"(?=\s*\S*:)"
_SPEC_D = r"(?=\s*\S*\d)"

# Wording that is a forwarding instruction wherever it appears, quoted or not.
_RECIPE_PROSE_SOURCE = r"""
    \btunnel\w* | \bautossh\b
    | \bport[-\s]?forward\w*
    | \bLocalForward\b | \bRemoteForward\b | \bDynamicForward\b
    | \bforward\w*\s+(the\s+)?port\b | \bforwarded\s+port\b
"""

# Flag forms for a line with no `ssh` command on it to parse - a config-file
# fragment, a snippet quoted out of context.
_RECIPE_FLAG_SOURCE = rf"""
    (?-i:-N\s+-L)
    | \s-\w*(?-i:[LR]){_SPEC_LR}
    | \s-\w*(?-i:D){_SPEC_D}
"""

# The OPERATOR RUNBOOK legitimately names the administration channel - the
# deployment and credential commands are run over it - so only the forwarding
# half applies there. "Shell access is required to run these commands" must
# stay sayable; teaching a forwarded port must not.
RECIPE_PROSE = re.compile(_RECIPE_PROSE_SOURCE, re.IGNORECASE | re.VERBOSE)
RECIPE_FLAGS = re.compile(_RECIPE_FLAG_SOURCE, re.IGNORECASE | re.VERBOSE)

# The SHIPPED CLIENT SURFACE may not name the administration channel at all,
# outside the one allowlisted note: the client does not use it, and a mention
# there is how the revoked design comes back. Everything the runbook rule
# catches, this one catches too - it is the same two patterns plus the bare
# name.
CLIENT_SURFACE_ONLY = re.compile(r"\bssh\b | \bsshd\b", re.IGNORECASE | re.VERBOSE)

# Flags that consume a value, from `ssh -h` (OpenSSH 9.6: `-B bind_interface`
# and `-P tag` are in it and were missed once). The value may be the next
# token or attached to the letter, which is what makes an option cluster
# readable at all: in `-oLogLevel=ERROR` the `o` takes everything after it, so
# the `L` in `LogLevel` is part of a VALUE and not a forward.
_SSH_VALUE_FLAGS = set("BbcDEeFIiJLlmOoPpQRSWw")
_SSH_FORWARD_FLAGS = set("LRD")
_SSH_COMMAND = re.compile(r"\bssh\b", re.IGNORECASE)
# The same forwarding, configured instead of flagged: `-oLocalForward=…`,
# `-o DynamicForward=1080`, or a line in a config file. Attached to the `o`
# there is no word boundary in front of it, so the prose pattern cannot see it.
_FORWARD_DIRECTIVE = re.compile(r"(Local|Remote|Dynamic)Forward", re.IGNORECASE)


def _ssh_tokens(tail: str) -> list[str]:
    """Shell tokens, with concatenated quoting handled.

    `-oProxyCommand="ssh jump nc %h %p"` is ONE argument: the quote starts
    mid-token. POSIX mode joins adjacent quoted and unquoted segments, which
    non-POSIX mode does not - and getting that wrong made the walk mistake
    `jump` for the destination and miss the forward after it.
    """
    try:
        return shlex.split(tail, posix=True)
    except ValueError:
        # An unbalanced quote is not a command; fall back to a plain split
        # rather than dropping the line from the scan entirely.
        return tail.split()


def _ssh_option_flags(line: str) -> set[str]:
    """The option LETTERS that ssh itself is given on this line.

    `ssh [options] destination [command [argument ...]]`. The walk reads
    option tokens letter by letter and stops a token at the first
    value-taking letter, because everything after that letter is its value;
    it stops the whole section at the first token that is not an option and
    is not a value, because that is the destination and what follows runs on
    the far side.

    Returning LETTERS rather than text is what removes the last guess: inside
    ssh's own options, `-L`, `-R` and `-D` are forwarding flags whatever their
    argument looks like, so a socket-to-socket forward and a bare `-R 1080`
    need no shape rule at all.
    """
    flags: set[str] = set()
    for match in _SSH_COMMAND.finditer(line):
        pending_letter = ""
        for token in _ssh_tokens(line[match.end():]):
            if pending_letter:
                if pending_letter == "o" and _FORWARD_DIRECTIVE.search(token):
                    flags.add("L")
                pending_letter = ""
                continue
            if not token.startswith("-") or token == "-":
                break  # the destination
            for index, letter in enumerate(token[1:], start=1):
                if not letter.isalpha():
                    break
                flags.add(letter)
                if letter in _SSH_VALUE_FLAGS:
                    # The rest of this token, or the next one, is its value.
                    attached = token[index + 1:]
                    if attached:
                        # `-oLocalForward=…` is a forward that neither the
                        # letter walk nor the prose pattern can see: the
                        # directive is concatenated to the `o`, so there is no
                        # word boundary in front of it.
                        if letter == "o" and _FORWARD_DIRECTIVE.search(attached):
                            flags.add("L")
                    else:
                        pending_letter = letter
                    break
    return flags


def _forwarding_hit(line: str, *, strict: bool) -> bool:
    """Prose anywhere on the line; flags only in SSH's own option section."""
    if RECIPE_PROSE.search(line):
        return True
    if _SSH_COMMAND.search(line):
        if _ssh_option_flags(line) & _SSH_FORWARD_FLAGS:
            return True
    elif RECIPE_FLAGS.search(line):
        # A config-file forward has no `ssh` on the line at all.
        return True
    return bool(strict and CLIENT_SURFACE_ONLY.search(line))

# Which pattern applies where. Anything not listed gets the strict one - and
# deploy/docker-compose.yml deliberately stays strict: the revoked claim lived
# in a comment in that file, describing how the CLIENT reaches the service, so
# it is client surface for this purpose even though operators read it.
RECIPE_ONLY_PATHS = {
    "docs/deployment.md",
    "deploy/vps-update.sh",
    "deploy/entrypoint.sh",
}

# The one place the client's documentation may name the administration
# channel: a note that exists precisely to say it is NOT the client's path.
# Pinned verbatim, so widening it is an edit to this list and not a side
# effect of rewording a paragraph.
ALLOWED_OPERATIONS_NOTES: dict[str, tuple[str, ...]] = {
    "client/README.md": (
        "> Operations note: SSH is how an operator administers the server host. It is",
    ),
    # The runbook's own prohibition sentence: it names the thing in order to
    # forbid it. A gate that made this unsayable would push the next author
    # towards a vaguer warning. It is kept on ONE unwrapped line in the
    # document, so reflowing the paragraph around it cannot turn a pin into
    # what looks like a policy violation.
    "docs/deployment.md": (
        "Inventing one here (a forwarded port, an open port, a new route) is exactly the decision this project stopped making by default.",
    ),
}


def _is_generated(parent_parts: tuple[str, ...]) -> bool:
    """Whether a path sits under a build artefact or a virtual environment."""
    return any(
        part in EXCLUDED_DIR_NAMES or part.endswith(EXCLUDED_DIR_SUFFIXES)
        for part in parent_parts
    )


def _scanned_paths() -> list[Path]:
    paths: list[Path] = []
    for tree in SCANNED_TREES:
        for path in sorted(tree.rglob("*")):
            if not path.is_file() or path.suffix not in SCANNED_SUFFIXES:
                continue
            if _is_generated(path.relative_to(tree).parts[:-1]):
                continue
            paths.append(path)
    paths.extend(path for path in SCANNED_FILES if path.is_file())
    assert paths, "the scan found no files at all, which would pass vacuously"
    return paths


def _logical_lines(text: str) -> list[tuple[int, str]]:
    """(first line number, joined text) for every line, continuations merged.

    A shell command split over a backslash continuation - `ssh -N \\` on one
    line, `-L 8787:127.0.0.1:8787 <vps>` on the next - matches nothing when
    each physical line is examined alone, and would have walked straight
    through a per-line scan. The pieces are joined before matching, and the
    offence is reported at the line the command starts on.
    """
    joined: list[tuple[int, str]] = []
    pending_number: int | None = None
    pending_parts: list[str] = []
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.rstrip()
        start = pending_number if pending_number is not None else number
        if stripped.endswith("\\"):
            pending_parts.append(stripped[:-1].strip())
            pending_number = start
            continue
        pending_parts.append(stripped.strip() if pending_parts else line)
        joined.append((start, " ".join(part for part in pending_parts if part)))
        pending_parts = []
        pending_number = None
    if pending_parts:
        joined.append(
            (pending_number or len(text.splitlines()), " ".join(pending_parts))
        )
    return joined


def _offending_lines(relative: str, text: str) -> list[str]:
    """Every line carrying a forwarding token, minus the allowlisted ones."""
    allowed = ALLOWED_OPERATIONS_NOTES.get(relative, ())
    strict = relative not in RECIPE_ONLY_PATHS
    offences = []
    for number, line in _logical_lines(text):
        if not _forwarding_hit(line, strict=strict):
            continue
        if line.strip() in allowed:
            continue
        offences.append(f"{relative}:{number}: {line.strip()}")
    return offences


def test_the_shipped_client_surface_names_no_forwarding_path() -> None:
    """AC20. The client must not depend on, document, or advertise a
    host-administration channel as the way it reaches the service."""
    offences: list[str] = []
    for path in _scanned_paths():
        offences.extend(
            _offending_lines(
                path.relative_to(ROOT).as_posix(), path.read_text(encoding="utf-8")
            )
        )

    assert not offences, (
        "the client surface may not present a host-administration channel as "
        "its path to the service:\n" + "\n".join(offences)
    )


def test_the_scan_actually_covers_the_files_it_claims_to() -> None:
    """A gate whose scope quietly shrinks stops being a gate. Each file below
    either carried the revoked wording or is shipped client surface, and all
    of them must stay in scope."""
    scanned = {path.relative_to(ROOT).as_posix() for path in _scanned_paths()}
    for required in (
        "client/src/wuwaterm_client/api.py",
        "client/src/wuwaterm_client/config.py",
        "client/src/wuwaterm_client/strings.py",
        "client/tests/test_api.py",
        "client/README.md",
        "client/main.py",
        "client/WuwaTerm.spec",
        "client/build.ps1",
        "client/pyproject.toml",
        "docs/deployment.md",
        "deploy/docker-compose.yml",
        # The web presentation layer. Every module of it, named individually
        # rather than as a directory: the failure this test exists to catch is
        # a scan whose scope quietly shrinks, and "the directory is listed"
        # would still be true if the recursion stopped returning files from it.
        "src/wuwaterm_api/web/__init__.py",
        "src/wuwaterm_api/web/app.py",
        "src/wuwaterm_api/web/render.py",
        "src/wuwaterm_api/web/session.py",
        "docs/web-presentation-layer.md",
    ):
        assert required in scanned, required
    # ...and nothing from a virtual environment or a build output, which are
    # third-party bytes and would make the gate unrunnable after a local build.
    assert not [path for path in scanned if "/.venv/" in path or "/dist/" in path]


def test_a_command_split_over_a_continuation_is_still_one_command() -> None:
    """The evasion a per-line scan cannot see.

    Neither physical line carries a matchable token on its own; joined, the
    command is the forwarded-port recipe the gate exists to keep out. The
    offence is reported at the line the command starts on.
    """
    split = 'ssh -N \\\n  -L 8787:127.0.0.1:8787 <vps>\n'
    assert _offending_lines("docs/deployment.md", split) == [
        "docs/deployment.md:1: ssh -N -L 8787:127.0.0.1:8787 <vps>"
    ]
    # ...and the same text in the client surface, which has the stricter rule.
    assert _offending_lines("client/build.ps1", split)
    # A trailing continuation at end of file must not swallow the last line.
    assert _offending_lines("docs/deployment.md", "ssh -N -L 1:2:3 host \\")


RECIPE_SPELLINGS = [
    "ssh -N -L 8787:127.0.0.1:8787 <vps>",
    "ssh -fNL 8787:127.0.0.1:8787 <vps>",
    "ssh -fNL8787:127.0.0.1:8787 <vps>",   # attached argument, valid syntax
    "ssh -L8787:127.0.0.1:8787 <vps>",
    "ssh -D 1080 <vps>",
    "ssh -R 8787:127.0.0.1:8787 <vps>",
    "autossh -M 0 <vps>",
    "LocalForward 8787 127.0.0.1:8787",
    "RemoteForward 8787 127.0.0.1:8787",
    "ssh -L *:8787:127.0.0.1:8787 <vps>",          # documented bind spelling
    "ssh -L /run/wuwaterm.sock:127.0.0.1:8787 <vps>",  # socket-path forward
    'ssh -L "8787:127.0.0.1:8787" <vps>',              # quoted forward spec
    "ssh -L /tmp/local.sock:/tmp/remote.sock <vps>",   # socket to socket, no port
    "ssh -D localhost:1080 <vps>",                     # dynamic, named bind
    "ssh -D [::1]:1080 <vps>",                         # dynamic, IPv6 bind
    'ssh -i "$HOME/.ssh/deploy key" -L 8787:127.0.0.1:8787 <vps>',  # quoted option value
    "ssh -N -f -L 8787:127.0.0.1:8787 <vps>",          # forward after other flags
    "ssh -B lo -L 8787:127.0.0.1:8787 <vps>",          # -B takes a value
    "ssh -P tag -L 8787:127.0.0.1:8787 <vps>",         # so does -P
    'ssh -oProxyCommand="ssh jump nc %h %p" -L 8787:127.0.0.1:8787 <vps>',
    "ssh -R 1080 <vps>",                               # remote dynamic forward
    "ssh -R /tmp/remote.sock <vps>",                   # remote socket forward
    "ssh -oLocalForward='8787 127.0.0.1:8787' <vps>",  # directive through -o
    "ssh -o RemoteForward=8787:127.0.0.1:8787 <vps>",
    "ssh -oDynamicForward=1080 <vps>",
    "DynamicForward 1080",
    "set up a port-forward from this computer",
    "the desktop reaches the service through a forwarded port",
    "try forwarding the port instead",
    "With the tunnel open, set the client's server address",
]

ORDINARY_OPERATOR_COMMANDS = [
    "SSH access to the host is required to run these deployment commands.",
    # Lowercase flags: the IGNORECASE half of the false-positive class.
    "ssh -l deploy <vps>",
    "ssh <vps> 'cd /opt/wuwaterm/current && docker compose up -d'",
    "ssh -p 2222 -i ~/.ssh/deploy_key <vps>",
    "ssh -o StrictHostKeyChecking=yes <vps>",
    # Uppercase flags that forward nothing: the half that dropping the word
    # boundary re-opened. `chown -R` is ordinary deployment work.
    "ssh <vps> 'chown -R deploy:deploy /opt/wuwaterm'",
    "ssh <vps> 'cp -R current previous'",
    "ssh <vps> 'curl -L https://example.com/readyz'",
    "ssh -oLogLevel=ERROR <vps>",
    "ssh <vps> 'kill -TERM 1234'",
    # Uppercase flags with a NUMERIC argument, inside the quoted remote
    # command: the residue both reviewers named after the previous head.
    "ssh <vps> 'chmod -R 755 /opt/wuwaterm'",
    "ssh <vps> 'kill -USR1 1234'",
    "ssh <vps> 'curl -L 127.0.0.1:8787/readyz'",
    "ssh <vps> 'cp -R state state.backup'",
    # An UNQUOTED remote command: the destination ends ssh's options whether
    # or not what follows is quoted.
    "ssh <vps> curl -L https://example.com/readyz",
    "ssh <vps> chmod -R 755 /opt/wuwaterm",
]


@pytest.mark.parametrize("line", RECIPE_SPELLINGS)
def test_every_spelling_of_the_recipe_is_caught_in_both_surfaces(line: str) -> None:
    """One source for the forwarding half means the strict rule is a superset
    of the lenient one by construction. Each spelling below is a way the
    revoked instruction can be written; `ssh -fNL8787:…` is the one that
    escaped both the pattern and the four literals in the deploy tests."""
    assert _offending_lines("docs/deployment.md", line + "\n"), line
    assert _offending_lines("client/README.md", line + "\n"), line


@pytest.mark.parametrize("line", ORDINARY_OPERATOR_COMMANDS)
def test_ordinary_operator_commands_do_not_fail_the_runbook_gate(line: str) -> None:
    """The whole point of the two-pattern split. `-l`, `-d` and `-r` are
    ordinary flags, and the patterns are compiled IGNORECASE, so without the
    scoped-case group these would each have been a CI failure on an accurate
    sentence."""
    assert _offending_lines("docs/deployment.md", line + "\n") == [], line


def test_the_runbook_may_still_describe_operator_access() -> None:
    """A gate that forbids an accurate operations sentence pushes the next
    author towards a vaguer one. The runbook may name the administration
    channel; it may not teach a forwarded port."""
    assert _offending_lines(
        "docs/deployment.md",
        "SSH access to the host is required to run these deployment commands.\n",
    ) == []
    assert _offending_lines(
        "docs/deployment.md", "ssh -fNL 8787:127.0.0.1:8787 <vps>\n"
    )
    assert _offending_lines("docs/deployment.md", "Open a tunnel to the API port.\n")
    # The client surface keeps the strict rule: the same first sentence fails
    # there, because the client has no business naming that channel at all.
    assert _offending_lines(
        "client/src/wuwaterm_client/api.py",
        "# SSH access to the host is required to run these commands\n",
    )


# Sentences that were REALLY on the shipped surface before this branch, taken
# from the gen-3 inventory rather than invented. `RECIPE_SPELLINGS` above is
# the constructed set; this one is the historical evidence that the gate would
# have caught the thing it was written for.
HISTORICAL_WORDING = [
    "ssh -N -L 8787:127.0.0.1:8787 user@host",
    "# the owner desktop reaches it through the existing SSH entry point",
    "With the tunnel open, set the client's server address",
    "an SSH tunnel from this computer to that loopback port",
    "The supported address is the local end of an SSH tunnel",
    "LocalForward 8787 127.0.0.1:8787",
]


@pytest.mark.parametrize("line", HISTORICAL_WORDING)
def test_the_scanner_catches_the_wording_it_exists_for(line: str) -> None:
    """The gate is only worth its green tick if it is known to fail. Each of
    these was really on the shipped surface before this change - they are the
    lines the gen-3 inventory listed - run through the same function the
    repository scan uses.

    The second case also shows the allowlist is a per-line exemption and not
    a per-file one: the same file that carries the operations note still
    fails on any other line.
    """
    assert _offending_lines("client/README.md", line) == [
        f"client/README.md:1: {line.strip()}"
    ]


def _exempted_occurrences(allowlist: dict[str, tuple[str, ...]]) -> int:
    """How many LINES in the repository an allowlist actually exempts.

    Not `len(dict)` and not the number of entries: exemption is by text, so
    one entry exempts every line in that file with that text. Counting what
    is really exempted is the only number worth pinning - the mechanism's
    promise is that widening it is a decision, and a duplicate line is a
    widening nobody had to write down.
    """
    total = 0
    for relative, lines in allowlist.items():
        present = [
            line.strip()
            for line in (ROOT / relative).read_text(encoding="utf-8").splitlines()
        ]
        for allowed in lines:
            total += present.count(allowed)
    return total


def test_the_allowlisted_operations_note_is_present_and_singular() -> None:
    """An allowlist that no longer matches anything is dead configuration,
    and an allowlist that grows without review is the hole itself."""
    for relative, lines in ALLOWED_OPERATIONS_NOTES.items():
        text = (ROOT / relative).read_text(encoding="utf-8")
        stripped = {line.strip() for line in text.splitlines()}
        for allowed in lines:
            assert allowed in stripped, f"{relative}: {allowed}"
    # Two exempted lines in the whole repository - counted as occurrences, so
    # a second copy of an exempted line is a failure and not a free pass.
    assert _exempted_occurrences(ALLOWED_OPERATIONS_NOTES) == 2
    # Each note says what it is for; without this they could be reduced to a
    # bare mention and still pass.
    assert "not part of this client's path" in (
        ROOT / "client" / "README.md"
    ).read_text(encoding="utf-8")
    assert "is exactly the decision this project stopped making" in (
        ROOT / "docs" / "deployment.md"
    ).read_text(encoding="utf-8")


# (c) Certificate verification: not a setting, not a flag, not anywhere.
#
# This regex is a TRIPWIRE, not the guarantee. Verification can be weakened in
# ways no text scan will see (`CERT_OPTIONAL`, a setattr, an indirection), and
# what actually proves the property is
# client/tests/test_transport_security.py::
# test_certificate_verification_is_on_for_the_client_it_actually_builds, which
# inspects the SSL context the client hands to its connection pool. This gate
# catches the obvious edit early and in the repository suite, where it runs on
# every pull request without the client's dependencies.

INSECURE_TLS = re.compile(
    r"""
    verify\s*=\s*False
    | check_hostname\s*=\s*False
    | CERT_NONE
    | VERIFY_NONE
    | _create_unverified_context
    | _create_default_https_context\s*=
    | create_default_context\s*=\s*\w*_create_unverified
    # `-k` anywhere in a short-option cluster: `curl -ksS`, `curl -kL`. The
    # lookbehind keeps `--key` out, which is a different option entirely.
    | curl[^\n]*(?<![-\w])-[a-zA-Z0-9]*k[a-zA-Z0-9]*\b
    | curl[^\n]*--insecure\b
    """,
    re.VERBOSE,
)

TLS_SCANNED_TREES = (
    # The whole client tree, not client/src: client/main.py is the packaged
    # entry point and executes before anything under src does, so a weakened
    # default SSL context assigned there would run in the shipped application
    # and be invisible to a src-only scan.
    ROOT / "client",
    ROOT / "src",
    ROOT / "scripts",
)

# Two lines name weakened verification in order to keep it out: the comment
# that explains the hazard, and the negative test that builds an unverified
# transport and asserts the client refuses it. Pinned verbatim, like the
# operations note above, so an exemption is a decision and not a side effect.
ALLOWED_INSECURE_TLS_LINES: dict[str, tuple[str, ...]] = {
    "client/src/wuwaterm_client/api.py": (
        "`AsyncHTTPTransport(verify=False)` would otherwise slip past a guarantee",
    ),
    "client/tests/test_transport_security.py": (
        "unverified = httpx.AsyncHTTPTransport(verify=False)",
    ),
}


def _insecure_tls_offences(relative: str, text: str) -> list[str]:
    """Continuations joined first, exactly as the wording gate does.

    `curl --silent \\` on one line and `-k https://…` on the next is one
    command, and reading physical lines would have let it through the scan of
    the shell scripts this gate had just gained.
    """
    allowed = ALLOWED_INSECURE_TLS_LINES.get(relative, ())
    offences = []
    for number, line in _logical_lines(text):
        if INSECURE_TLS.search(line) and line.strip() not in allowed:
            offences.append(f"{relative}:{number}: {line.strip()}")
    return offences


def _tls_scanned_paths() -> list[Path]:
    paths: list[Path] = []
    for tree in TLS_SCANNED_TREES:
        for path in sorted(tree.rglob("*.py")):
            if _is_generated(path.relative_to(tree).parts[:-1]):
                continue
            paths.append(path)
    # The deployment scripts, and the guide that reproduces their commands
    # verbatim: the readiness probe there is a `urllib.request.urlopen` call,
    # and the edit that would weaken it - an unverified SSL context - is
    # exactly what this pattern is for. A copy that is documented but not
    # scanned is the copy that rots.
    paths.extend(sorted((ROOT / "deploy").glob("*.sh")))
    paths.append(ROOT / "docs" / "deployment.md")
    return paths


def test_nothing_turns_certificate_verification_off() -> None:
    offences: list[str] = []
    scanned = 0
    for path in _tls_scanned_paths():
        scanned += 1
        offences.extend(
            _insecure_tls_offences(
                path.relative_to(ROOT).as_posix(),
                path.read_text(encoding="utf-8"),
            )
        )
    assert scanned, "the scan found no files, which would pass vacuously"
    assert not offences, "certificate verification may not be weakened:\n" + "\n".join(
        offences
    )


def test_the_tls_scanner_catches_a_real_disabling_line() -> None:
    """Including in the two files that hold an exemption: the exemption is
    one pinned line, not a licence for the file."""
    assert _insecure_tls_offences(
        "client/src/wuwaterm_client/api.py",
        "        self._client = httpx.AsyncClient(verify=False)\n",
    ) == ["client/src/wuwaterm_client/api.py:1: self._client = httpx.AsyncClient(verify=False)"]
    assert _insecure_tls_offences("src/wuwaterm/sentence.py", "ctx.check_hostname = False\n")


def test_the_tls_scan_reaches_the_operator_commands_as_well_as_the_client() -> None:
    """The scripts and the guide run the same readiness probe.

    `deploy/vps-update.sh` and `docs/deployment.md` carry the same
    `urllib.request.urlopen` command; if one of them ever gained an
    unverified SSL context, a client-only scan would not have seen it. The
    `curl` branch of the pattern has no producer in this repository today -
    it is there for the shell one-liner someone reaches for first.
    """
    scanned = {path.relative_to(ROOT).as_posix() for path in _tls_scanned_paths()}
    for required in (
        "client/src/wuwaterm_client/api.py",
        "client/main.py",
        "deploy/vps-update.sh",
        "deploy/entrypoint.sh",
        "docs/deployment.md",
    ):
        assert required in scanned, required
    assert _insecure_tls_offences(
        "client/main.py", "ssl._create_default_https_context = _unverified\n"
    )
    assert _insecure_tls_offences("deploy/vps-update.sh", 'curl -sk "$url"\n')
    # A continued command is one command here too, exactly as the wording gate
    # reads it - and a shell script is where a continuation actually appears.
    assert _insecure_tls_offences(
        "deploy/vps-update.sh", 'curl --silent \\\n  -k "$url"\n'
    ) == ['deploy/vps-update.sh:1: curl --silent -k "$url"']
    assert _insecure_tls_offences(
        "docs/deployment.md", "urlopen(url, context=ssl._create_unverified_context())\n"
    )


def test_the_tls_exemptions_still_describe_real_lines() -> None:
    """An exemption whose line is gone is dead configuration, and an
    exemption list that grows without review is the hole itself."""
    for relative, lines in ALLOWED_INSECURE_TLS_LINES.items():
        present = {
            line.strip()
            for line in (ROOT / relative).read_text(encoding="utf-8").splitlines()
        }
        for allowed in lines:
            assert allowed in present, f"{relative}: {allowed}"
    # Occurrences, not entries: the negative test constructs its unverified
    # transport twice, and both copies are exempted by the one entry - so the
    # number that has to be reviewed is three, not two.
    assert _exempted_occurrences(ALLOWED_INSECURE_TLS_LINES) == 3


def test_the_client_asks_httpx_for_verification_in_writing() -> None:
    """Removal of the explicit request has to be a visible edit."""
    api = (ROOT / "client" / "src" / "wuwaterm_client" / "api.py").read_text(
        encoding="utf-8"
    )
    assert "verify=True" in api
    assert "trust_env=False" in api


# D5': the client is an HTTP client and nothing else.

PROCESS_AND_KEY_TOKENS = re.compile(
    r"""
    \bimport\s+subprocess\b | \bfrom\s+subprocess\s+import\b
    | \bsubprocess\.\w+ | \bPopen\s*\(
    | \bos\.system\b | \bos\.exec\w*\b | \bos\.spawn\w*\b | \bos\.popen\b
    | \bcreate_subprocess_(exec|shell)\b
    | \bimport\s+multiprocessing\b | \bfrom\s+multiprocessing\s+import\b
    | \bpty\.spawn\b | \bos\.startfile\b
    | \bimport\s+paramiko\b | \bimport\s+asyncssh\b | \bimport\s+fabric\b
    | \bQProcess\b
    | \bid_rsa\b | \bid_ed25519\b | \bknown_hosts\b | \bPRIVATE\s+KEY\b
    """,
    re.VERBOSE,
)


def _shipped_client_python() -> list[Path]:
    """The client APPLICATION's Python: what a packaged build executes.

    `client/src` is not all of it - `client/main.py` is the PyInstaller entry
    point, and a helper started from there would run in exactly the same
    application. `client/tests` is deliberately NOT in it: tests do not ship,
    and one that shells out to inspect a packaged build should not trip a gate
    about what the application does.
    """
    tree = ROOT / "client"
    paths = [
        path
        for path in sorted(tree.rglob("*.py"))
        if not _is_generated(path.relative_to(tree).parts[:-1])
        and "tests" not in path.relative_to(tree).parts[:-1]
    ]
    assert paths, "no client Python found, which would pass vacuously"
    return paths


def test_the_client_starts_no_processes_and_carries_no_keys() -> None:
    """The application reaches the service by making HTTP requests. It does
    not start helpers, and it holds exactly one credential - the device
    token, in the OS credential store - and no key material of its own."""
    scanned = {path.relative_to(ROOT).as_posix() for path in _shipped_client_python()}
    assert "client/main.py" in scanned
    assert "client/src/wuwaterm_client/app.py" in scanned

    offences: list[str] = []
    for path in _shipped_client_python():
        for number, line in enumerate(
            path.read_text(encoding="utf-8").splitlines(), start=1
        ):
            if PROCESS_AND_KEY_TOKENS.search(line):
                offences.append(
                    f"{path.relative_to(ROOT).as_posix()}:{number}: {line.strip()}"
                )
    assert not offences, "the client may not start processes or hold keys:\n" + "\n".join(
        offences
    )
