"""Transport-hardening gates for the desktop client.

Two properties are pinned here, both of them about what the client will do
with the device credential before any request is sent:

(b) an address that would carry the token to another machine in the clear is
    refused by the transport itself, with a stable error code; and
(c) certificate verification is on for every HTTPS request, with no way to
    turn it off.

No Qt, no network, no running server.
"""

from __future__ import annotations

import asyncio
import ssl
from pathlib import Path

import httpx
import pytest

from wuwaterm_client import strings
from wuwaterm_client.api import ApiClient
from wuwaterm_client.config import ClientConfig, endpoint_is_confidential, usable_base_url
from wuwaterm_client.errors import ERROR_INSECURE_ENDPOINT, ClientError

LOOPBACK = "http://127.0.0.1:8787"

# Directories that hold third-party or generated bytes rather than client
# code. Kept in step with EXCLUDED_DIR_NAMES in
# tests/test_client_transport_policy.py; the two suites cannot import each
# other (different roots, different interpreters), so the duplication is
# deliberate and the lists are written to match.
EXCLUDED_DIRS = {
    ".venv",
    "venv",
    "build",
    "dist",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
}

REFUSED_ADDRESSES = [
    "http://198.51.100.7:8787",
    "http://api.example.com",
    "http://api.example.com:8787/wuwaterm-api",
    "http://[2001:db8::1]:8787",
    "http://127.0.0.1.example.com:8787",  # loopback-looking, not loopback
    "ftp://example.com",
    "//example.com/wuwaterm-api",  # no scheme at all
    "example.com:8787",
]

ACCEPTED_ADDRESSES = [
    "https://api.example.com",
    "https://api.example.com:8443/wuwaterm-api",
    LOOPBACK,
    "http://localhost:8787",
    "http://[::1]:8787",
]


def _close(client: ApiClient) -> None:
    asyncio.run(client.aclose())


def _parts(url: httpx.URL) -> tuple[str, str, int, str]:
    """Scheme, host, port and path prefix - everything an address decides.

    The path is part of it on purpose: an endpoint may be published under a
    prefix, and a comparison that ignored it would stay green while every
    request went somewhere else. httpx normalises a base path with a trailing
    slash, so both sides are normalised here.
    """
    port = url.port or (443 if url.scheme == "https" else 80)
    path = url.path if url.path.endswith("/") else url.path + "/"
    return (url.scheme, url.host, port, path)


@pytest.mark.parametrize("address", REFUSED_ADDRESSES)
def test_the_transport_refuses_an_address_it_cannot_protect(address: str) -> None:
    """Refused where the transport is built, not only where it is typed.

    The settings dialog validates too, but this constructor is reachable
    without it - a hand-edited configuration file, a future caller - and a
    check that lives only in the dialog is not a transport guarantee.
    """
    with pytest.raises(ClientError) as raised:
        ApiClient(address)

    assert raised.value.code == ERROR_INSECURE_ENDPOINT
    assert raised.value.message == strings.ERROR_MSG_INSECURE_ENDPOINT
    # The same address is refused by the setting validator and by the policy
    # predicate, so the three cannot drift apart silently.
    assert usable_base_url(address) is False
    assert endpoint_is_confidential(address) is False


@pytest.mark.parametrize(
    "address",
    [
        "https://device:secret@api.example.com",       # a second, unmanaged credential
        "https://api.example.com?token=secret",        # silently dropped when joined
        "https://api.example.com#fragment",
        "https://api.example.com:notaport",
    ],
)
def test_the_transport_is_no_more_permissive_than_the_settings_field(address: str) -> None:
    """The layer closest to the network must not be the weakest one.

    Each of these is confidential in transit and still unusable as a stored
    address; the settings dialog and the on-disk loader have always refused
    them, and the constructor now applies the same predicate rather than the
    narrower confidentiality rule inside it.
    """
    # Confidential in transit, and still not a usable stored address: this is
    # exactly the gap between the two predicates.
    assert endpoint_is_confidential(address) is True
    assert usable_base_url(address) is False
    with pytest.raises(ClientError) as raised:
        ApiClient(address)
    assert raised.value.code == ERROR_INSECURE_ENDPOINT


@pytest.mark.parametrize("address", ACCEPTED_ADDRESSES)
def test_https_anywhere_and_plain_http_to_this_machine_are_accepted(address: str) -> None:
    """The rule must not be so strict that it refuses the supported forms:
    a gate that rejects everything proves nothing about the one case."""
    assert endpoint_is_confidential(address) is True
    client = ApiClient(address, token_provider=lambda: None)
    try:
        assert _parts(client._client.base_url) == _parts(httpx.URL(address))
    finally:
        _close(client)


def test_the_address_that_is_validated_is_the_address_that_is_used() -> None:
    """Whitespace made the two differ.

    `usable_base_url` strips before parsing, so `" https://api.example.com "`
    is approved in its stripped form; handing httpx the raw string meant the
    approved address and the configured one were not the same address - httpx
    reads a leading space as the start of a relative URL.
    """
    padded = "  https://api.example.com  "
    client = ApiClient(padded, token_provider=lambda: None)
    try:
        assert _parts(client._client.base_url) == ("https", "api.example.com", 443, "/")
        client.update_base_url("\thttps://other.example.com\n")
        assert _parts(client._client.base_url) == (
            "https",
            "other.example.com",
            443,
            "/",
        )
    finally:
        _close(client)


def test_a_refused_address_leaves_the_running_client_where_it_was() -> None:
    """A rejected settings change must not half-apply: the previous address
    stays in effect, so the owner keeps a working client."""
    client = ApiClient(LOOPBACK, token_provider=lambda: None)
    try:
        with pytest.raises(ClientError) as raised:
            client.update_base_url("http://198.51.100.7:8787")
        assert raised.value.code == ERROR_INSECURE_ENDPOINT
        # Compared per component rather than by string prefix: a prefix test
        # on a URL is the classic incomplete check, and it would also pass
        # for an address that merely starts the same way.
        assert _parts(client._client.base_url) == _parts(httpx.URL(LOOPBACK))

        client.update_base_url("https://api.example.com")
        assert _parts(client._client.base_url) == ("https", "api.example.com", 443, "/")
    finally:
        _close(client)


def test_a_stored_configuration_can_never_carry_a_refused_address(tmp_path) -> None:
    """End to end for the path a real launch takes: whatever is on disk,
    ClientConfig.load falls back rather than handing the transport an
    address it will refuse."""
    (tmp_path / "config.json").write_text(
        '{"base_url": "http://198.51.100.7:8787"}', encoding="utf-8"
    )
    config = ClientConfig.load(tmp_path)

    assert config.base_url == ClientConfig().base_url
    client = ApiClient.from_config(config)
    _close(client)


def test_certificate_verification_is_on_for_the_client_it_actually_builds() -> None:
    """Not "the default is safe" - the SSL context this client hands to the
    connection pool is inspected, and must require a certificate and check
    the host name."""
    client = ApiClient("https://api.example.com", token_provider=lambda: None)
    try:
        transport = client._client._transport
        pool = getattr(transport, "_pool", None)
        context = getattr(pool, "_ssl_context", None)
        assert isinstance(context, ssl.SSLContext), (
            "could not reach the transport's SSL context; this assertion must "
            "be repaired rather than deleted, or the gate proves nothing"
        )
        assert context.verify_mode is ssl.CERT_REQUIRED
        assert context.check_hostname is True
    finally:
        _close(client)


def test_the_client_asks_for_verification_explicitly() -> None:
    """The httpx default is verification, and this pins that the client does
    not rely on that default staying what it is today."""
    recorded: dict[str, object] = {}
    original = httpx.AsyncClient

    class _Recording(original):  # type: ignore[misc, valid-type]
        def __init__(self, *args, **kwargs):
            recorded.update(kwargs)
            super().__init__(*args, **kwargs)

    httpx.AsyncClient = _Recording  # type: ignore[misc]
    try:
        client = ApiClient("https://api.example.com", token_provider=lambda: None)
    finally:
        httpx.AsyncClient = original  # type: ignore[misc]
    _close(client)

    assert recorded["verify"] is True
    assert recorded["trust_env"] is False


def test_the_client_exposes_no_way_to_turn_verification_off() -> None:
    """A constructor keyword is how an insecure toggle usually arrives."""
    import inspect

    parameters = inspect.signature(ApiClient.__init__).parameters
    for suspicious in ("verify", "insecure", "allow_insecure", "ssl_verify", "no_verify"):
        assert suspicious not in parameters, suspicious
    # The transport seam is private and is named so, because a MockTransport
    # handler is arbitrary in-process code: the guarantee is about what an
    # owner or a configuration can do, and the name says where that boundary
    # is. Nothing the application ships passes it.
    assert "transport" not in parameters
    assert "_test_transport" in parameters
    # Every Python file the packaged application executes, not just the
    # package directory: client/main.py is the PyInstaller entry point and
    # lives outside client/src.
    client_root = Path(inspect.getfile(ApiClient)).parents[2]
    assert (client_root / "main.py").is_file(), client_root
    application = [
        path
        for path in client_root.rglob("*.py")
        if "tests" not in path.relative_to(client_root).parts[:-1]
        and not any(
            part in EXCLUDED_DIRS or part.endswith(".egg-info")
            for part in path.relative_to(client_root).parts[:-1]
        )
    ]
    # Structural, not incidental: the entry point must be in the list that is
    # searched, not merely present on disk.
    assert "main.py" in {path.name for path in application}
    assert "api.py" in {path.name for path in application}
    callers = sorted(
        path.name
        for path in application
        if path.name != "api.py" and "_test_transport" in path.read_text(encoding="utf-8")
    )
    assert callers == [], f"the test seam is used by shipped code: {callers}"


def test_an_injected_transport_may_not_bring_weakened_tls() -> None:
    """The one remaining way in: `_test_transport=` is honoured by httpx INSTEAD of
    `verify=True`, so a transport built with verification off would have made
    the guarantee false through an argument that does not mention TLS."""
    unverified = httpx.AsyncHTTPTransport(verify=False)
    try:
        with pytest.raises(ClientError) as raised:
            ApiClient("https://api.example.com", _test_transport=unverified)
        assert raised.value.code == ERROR_INSECURE_ENDPOINT
    finally:
        asyncio.run(unverified.aclose())


def test_a_verifying_transport_is_still_accepted() -> None:
    """The check must discriminate, not ban the parameter: a real transport
    that does verify is exactly what production would build."""
    verifying = httpx.AsyncHTTPTransport(verify=True)
    client = ApiClient("https://api.example.com", _test_transport=verifying,
                       token_provider=lambda: None)
    _close(client)


def test_a_transport_whose_configuration_cannot_be_read_is_refused() -> None:
    """Unprovable is treated as unsafe: a transport this client cannot
    inspect could be doing anything with the credential."""

    class _Opaque(httpx.AsyncBaseTransport):
        async def handle_async_request(self, request):  # pragma: no cover
            raise AssertionError("never reached")

    with pytest.raises(ClientError) as raised:
        ApiClient("https://api.example.com", _test_transport=_Opaque())
    assert raised.value.code == ERROR_INSECURE_ENDPOINT


def test_a_transport_that_shows_a_verifying_context_but_uses_another_is_refused() -> None:
    """Inspecting attributes proves nothing about what a transport DOES.

    This one presents a perfectly good SSL context for inspection and would
    have sent the bearer credential down an unverified connection. The guard
    accepts exact types it can reason about, so a decoy never gets that far -
    and neither does a subclass, which could override the request method
    while inheriting the verifying pool.
    """

    class _Decoy(httpx.AsyncBaseTransport):
        def __init__(self, honest: httpx.AsyncHTTPTransport,
                     real: httpx.AsyncHTTPTransport) -> None:
            self._pool = honest._pool          # what an inspector sees
            self._real = real                  # what the request would use

        async def handle_async_request(self, request):  # pragma: no cover
            return await self._real.handle_async_request(request)

    honest = httpx.AsyncHTTPTransport(verify=True)
    unverified = httpx.AsyncHTTPTransport(verify=False)
    try:
        decoy = _Decoy(honest, unverified)
        # The decoy really would pass an attribute-only inspection.
        assert decoy._pool._ssl_context.verify_mode is ssl.CERT_REQUIRED
        with pytest.raises(ClientError) as raised:
            ApiClient("https://api.example.com", _test_transport=decoy)
        assert raised.value.code == ERROR_INSECURE_ENDPOINT

        class _Subclass(httpx.AsyncHTTPTransport):
            pass

        subclass = _Subclass(verify=True)
        try:
            with pytest.raises(ClientError):
                ApiClient("https://api.example.com", _test_transport=subclass)
        finally:
            asyncio.run(subclass.aclose())
    finally:
        asyncio.run(honest.aclose())
        asyncio.run(unverified.aclose())
